staging="file:///home/hduser/project/data/staging"
input="file:///home/hduser/project/data/input"
output="file:///home/hduser/project/data/output"
mySqlUrl="jdbc:mysql://localhost:3306"
jdbcJar="file:///home/hduser/project/data/mysql.jar"
model="file:///home/hduser/project/model"
download="file:///home/spark/Downloads"
